/**
 * The shim Cogpit puts first on every agent's PATH. agent-browser's first call
 * spawns a daemon that inherits that call's environment, so the shim is where
 * each session's profile, socket dir and Chromium flags get decided.
 *
 * macOS and Linux get one bash script. Windows gets the same routing as a Node
 * script plus two launchers for it: a `.cmd` for cmd.exe, PowerShell and
 * Cogpit's own spawns, and a bash delegate for Git Bash, which some agent
 * shell tools run there. agent-browser needs `node` on PATH to start its
 * daemon, so the launchers may rely on it too.
 */
import {
  accessSync,
  chmodSync,
  constants as fsConstants,
  mkdirSync,
  readFileSync,
  realpathSync,
  renameSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs"
import { join, posix, resolve, win32 } from "node:path"
import {
  BROWSER_NAME_RE,
  COGPIT_SESSION_ID_RE,
  DEFAULT_BROWSER,
  SHARED_RUN_NAME,
  THROWAWAY_PREFIX,
  binDir,
  nodeShimPath,
  shimPath,
} from "./paths"

export const SHIM_VERSION = 3

const BINARY_NAME = "agent-browser"
const NODE_SHIM_NAME = "agent-browser-shim.mjs"
const MARKER = `cogpit-shim v${SHIM_VERSION} — routes agent-browser into Cogpit's managed browser tree.`

/**
 * Chromium sets `navigator.webdriver` whenever a debugging port is open, and
 * bot checks such as Cloudflare's Turnstile refuse the page on that alone. A
 * user completing a human-verification step in the panel is not automation,
 * so a windowed browser runs with that signal off.
 */
const VISIBLE_BROWSER_ARGS = "--remote-debugging-port=0,--disable-blink-features=AutomationControlled"

export interface ShimOptions {
  /** A full Chrome or Chromium to open named browsers in a real window; null keeps them headless. */
  visibleBrowser?: string | null
  /** Which host's shim to render; defaults to this process's platform. */
  platform?: NodeJS.Platform
}

/** Escapes a value for interpolation inside bash double quotes. */
function shellQuoted(value: string): string {
  return value.replace(/[\\"$`]/g, (char) => `\\${char}`)
}

/**
 * Headless Chromium fails bot checks by user agent alone, so named browsers open
 * in a real window when a display can show one. macOS always has one; Linux
 * only when the agent's environment names an X or Wayland display. Setting
 * `COGPIT_BROWSER_HEADLESS` keeps them headless anyway. Throwaways stay
 * headless: nobody watches them.
 */
function renderVisibleBrowser(visibleBrowser: string | null, platform: NodeJS.Platform): string {
  if (!visibleBrowser || (platform !== "darwin" && platform !== "linux")) return ""
  const conditions = [`[ -z "\${COGPIT_BROWSER_HEADLESS:-}" ]`]
  if (platform === "linux") conditions.push(`[ -n "\${DISPLAY:-}\${WAYLAND_DISPLAY:-}" ]`)
  return `if ${conditions.join(" && ")}; then
export AGENT_BROWSER_HEADED=1
export AGENT_BROWSER_EXECUTABLE_PATH="${shellQuoted(visibleBrowser)}"
export AGENT_BROWSER_ARGS="${VISIBLE_BROWSER_ARGS}"
fi
`
}

export function renderShim(realBinary: string, options: ShimOptions = {}): string {
  const { visibleBrowser = null, platform = process.platform } = options
  return `#!/usr/bin/env bash
# ${MARKER}
# Regenerated by Cogpit on start; edits are lost.
set -euo pipefail
real="${shellQuoted(realBinary)}"
if [ ! -x "$real" ] || [ "$real" -ef "$0" ]; then
  echo "cogpit-shim: $real is not usable; restart Cogpit to refresh the shim" >&2
  exit 127
fi
valid_name() { local LC_ALL=C; [[ "$1" =~ ${BROWSER_NAME_RE.source} ]]; }
valid_sid()  { local LC_ALL=C; [[ "$1" =~ ${COGPIT_SESSION_ID_RE.source} ]]; }
[ -n "\${COGPIT_BROWSER_HOME:-}" ] || [ -n "\${HOME:-}" ] || exec "$real" "$@"
home="\${COGPIT_BROWSER_HOME:-$HOME/.cogpit/browser}"
name="\${AGENT_BROWSER_SESSION:-${DEFAULT_BROWSER}}"
prev=""
for arg in "$@"; do
  if [ "$prev" = "--session" ]; then name="$arg"; break; fi
  case "$arg" in --session=*) name="\${arg#--session=}"; break;; esac
  prev="$arg"
done
valid_name "$name" || exec "$real" "$@"
if [[ "$name" == ${THROWAWAY_PREFIX}* ]]; then
  sid="\${COGPIT_SESSION_ID:-}"
  valid_sid "$sid" || sid="${SHARED_RUN_NAME}"
  export AGENT_BROWSER_SOCKET_DIR="$home/run/$sid"
  mkdir -p "$AGENT_BROWSER_SOCKET_DIR"
  exec "$real" "$@"
fi
profile="$home/profiles/$name"
mkdir -p "$profile" "$home/run/${SHARED_RUN_NAME}"
printf '%s\\n' "\${COGPIT_SESSION_ID:-}" > "$profile/.driver"
export AGENT_BROWSER_SOCKET_DIR="$home/run/${SHARED_RUN_NAME}"
export AGENT_BROWSER_PROFILE="$profile"
export AGENT_BROWSER_ARGS="--remote-debugging-port=0"
${renderVisibleBrowser(visibleBrowser, platform)}exec "$real" "$@"
`
}

/**
 * The bash shim's routing, for hosts without bash on the agent's path. A real
 * binary that is a batch file goes through cmd.exe with the same quoting as
 * `binaryResolver`, since `shell: true` would join the arguments unescaped.
 */
export function renderNodeShim(realBinary: string): string {
  return `// ${MARKER}
// Regenerated by Cogpit on start; edits are lost.
import { spawnSync } from "node:child_process"
import { mkdirSync, realpathSync, statSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { fileURLToPath } from "node:url"

const real = ${JSON.stringify(realBinary)}
const NAME_RE = ${BROWSER_NAME_RE.toString()}
const SID_RE = ${COGPIT_SESSION_ID_RE.toString()}
const args = process.argv.slice(2)
const env = { ...process.env }

function isFile(path) {
  try { return statSync(path).isFile() } catch { return false }
}
function sameFile(a, b) {
  try { return realpathSync(a) === realpathSync(b) } catch { return false }
}
if (!isFile(real) || sameFile(real, fileURLToPath(import.meta.url))) {
  console.error(\`cogpit-shim: \${real} is not usable; restart Cogpit to refresh the shim\`)
  process.exit(127)
}

function quoteArgument(arg) {
  return \`"\${arg.replace(/(\\\\*)"/g, '$1$1\\\\"').replace(/(\\\\*)$/, "$1$1")}"\`
}
function escapeForCmd(text) {
  return text.replace(/([()[\\]%!^"\`<>&|;, *?])/g, "^$1")
}
function run() {
  const batch = process.platform === "win32" && /\\.(cmd|bat)$/i.test(real)
  const result = batch
    ? spawnSync(env.COMSPEC || "cmd.exe", ["/d", "/s", "/c", \`"\${[escapeForCmd(real), ...args.map((arg) => escapeForCmd(quoteArgument(arg)))].join(" ")}"\`], { env, stdio: "inherit", windowsVerbatimArguments: true })
    : spawnSync(real, args, { env, stdio: "inherit" })
  if (result.error) {
    console.error(\`cogpit-shim: \${result.error.message}\`)
    process.exit(127)
  }
  process.exit(result.status ?? 1)
}

const homeDir = process.platform === "win32" ? env.USERPROFILE || env.HOME : env.HOME
const home = env.COGPIT_BROWSER_HOME || (homeDir ? join(homeDir, ".cogpit", "browser") : null)
if (home === null) run()

let name = env.AGENT_BROWSER_SESSION || ${JSON.stringify(DEFAULT_BROWSER)}
for (let i = 0; i < args.length; i++) {
  if (args[i] === "--session") {
    if (i + 1 < args.length) name = args[i + 1]
    break
  }
  if (args[i].startsWith("--session=")) {
    name = args[i].slice("--session=".length)
    break
  }
}
if (!NAME_RE.test(name)) run()

if (name.startsWith(${JSON.stringify(THROWAWAY_PREFIX)})) {
  const sid = SID_RE.test(env.COGPIT_SESSION_ID ?? "") ? env.COGPIT_SESSION_ID : ${JSON.stringify(SHARED_RUN_NAME)}
  env.AGENT_BROWSER_SOCKET_DIR = join(home, "run", sid)
  mkdirSync(env.AGENT_BROWSER_SOCKET_DIR, { recursive: true })
  run()
}

const profile = join(home, "profiles", name)
const sharedRun = join(home, "run", ${JSON.stringify(SHARED_RUN_NAME)})
mkdirSync(profile, { recursive: true })
mkdirSync(sharedRun, { recursive: true })
writeFileSync(join(profile, ".driver"), \`\${env.COGPIT_SESSION_ID ?? ""}\\n\`)
env.AGENT_BROWSER_SOCKET_DIR = sharedRun
env.AGENT_BROWSER_PROFILE = profile
env.AGENT_BROWSER_ARGS = "--remote-debugging-port=0"
run()
`
}

export function renderCmdLauncher(): string {
  return `@echo off\r\nnode "%~dp0${NODE_SHIM_NAME}" %*\r\n`
}

export function renderBashLauncher(): string {
  return `#!/usr/bin/env bash
# ${MARKER}
# Regenerated by Cogpit on start; edits are lost.
exec node "$(dirname "$0")/${NODE_SHIM_NAME}" "$@"
`
}

function hasContent(path: string, script: string): boolean {
  try {
    return readFileSync(path, "utf8") === script
  } catch {
    return false
  }
}

function writeExecutable(path: string, script: string): void {
  if (!hasContent(path, script)) {
    mkdirSync(binDir(), { recursive: true })
    const tmp = `${path}.tmp`
    writeFileSync(tmp, script, { mode: 0o755 })
    renameSync(tmp, path)
  }
  chmodSync(path, 0o755)
}

/** Every file the shim occupies on this host, with the script each one holds. */
function shimFiles(
  realBinary: string,
  options: ShimOptions,
  platform: NodeJS.Platform,
): Array<[path: string, script: string]> {
  if (platform !== "win32") return [[shimPath(platform), renderShim(realBinary, options)]]
  return [
    [nodeShimPath(), renderNodeShim(realBinary)],
    [shimPath(platform), renderCmdLauncher()],
    [join(binDir(), BINARY_NAME), renderBashLauncher()],
  ]
}

export function ensureShim(realBinary: string | null, options: ShimOptions = {}): { path: string | null } {
  const platform = options.platform ?? process.platform
  if (realBinary === null) {
    for (const [path] of shimFiles("", options, platform)) rmSync(path, { force: true })
    return { path: null }
  }
  for (const [path, script] of shimFiles(realBinary, options, platform)) writeExecutable(path, script)
  return { path: shimPath(platform) }
}

function canonical(dir: string): string {
  try {
    return realpathSync(dir)
  } catch {
    return resolve(dir)
  }
}

function isExecutableFile(candidate: string): boolean {
  try {
    accessSync(candidate, fsConstants.X_OK)
    return statSync(candidate).isFile()
  } catch {
    return false
  }
}

function isRegularFile(candidate: string): boolean {
  try {
    return statSync(candidate).isFile()
  } catch {
    return false
  }
}

export interface FindRealOptions {
  platform?: NodeJS.Platform
  arch?: string
  /** Injected by tests; defaults to a real filesystem probe. */
  isFile?: (candidate: string) => boolean
}

/**
 * Windows has no execute bit, so launchability comes from the extension. npm's
 * `.cmd` shim just runs the native binary the package vendors next to it, and
 * that binary is what the Node shim spawns: a `.cmd` needs cmd.exe in between.
 */
function findRealOnWindows(dirs: string[], options: FindRealOptions): string | null {
  const isFile = options.isFile ?? isRegularFile
  const vendored = win32.join("node_modules", BINARY_NAME, "bin", `${BINARY_NAME}-win32-${options.arch ?? process.arch}.exe`)
  for (const dir of dirs) {
    const native = win32.join(dir, `${BINARY_NAME}.exe`)
    if (isFile(native)) return native
    const batch = win32.join(dir, `${BINARY_NAME}.cmd`)
    if (!isFile(batch)) continue
    const packaged = win32.join(dir, vendored)
    return isFile(packaged) ? packaged : batch
  }
  return null
}

export function findRealAgentBrowser(env: NodeJS.ProcessEnv = process.env, options: FindRealOptions = {}): string | null {
  const platform = options.platform ?? process.platform
  const path = platform === "win32" ? win32 : posix
  const shimDir = canonical(binDir())
  const dirs = (env.PATH ?? "").split(path.delimiter).filter((entry) => entry && canonical(entry) !== shimDir)
  if (platform === "win32") return findRealOnWindows(dirs, options)
  const isFile = options.isFile ?? isExecutableFile
  for (const dir of dirs) {
    const candidate = path.join(dir, BINARY_NAME)
    if (isFile(candidate)) return candidate
  }
  return null
}

const MAC_BROWSER_APPS = ["Google Chrome.app/Contents/MacOS/Google Chrome", "Chromium.app/Contents/MacOS/Chromium"]
const LINUX_BROWSER_NAMES = ["google-chrome", "google-chrome-stable", "chromium", "chromium-browser"]

/**
 * A full Chrome or Chromium that can open a window. agent-browser's own download
 * is the headless shell, which cannot, so this is what a visible browser runs on.
 */
export function findVisibleBrowser(env: NodeJS.ProcessEnv = process.env, platform = process.platform): string | null {
  return visibleBrowserCandidates(env, platform).find(isExecutableFile) ?? null
}

/** Every place a visible browser may live, best first. */
function visibleBrowserCandidates(env: NodeJS.ProcessEnv, platform: NodeJS.Platform): string[] {
  if (platform === "darwin") {
    const roots = ["/Applications", ...(env.HOME ? [join(env.HOME, "Applications")] : [])]
    return MAC_BROWSER_APPS.flatMap((app) => roots.map((root) => join(root, app)))
  }
  if (platform !== "linux") return []
  const dirs = (env.PATH ?? "").split(posix.delimiter).filter(Boolean)
  return LINUX_BROWSER_NAMES.flatMap((name) => dirs.map((dir) => join(dir, name)))
}
