/**
 * The bash shim Cogpit puts first on every agent's PATH. agent-browser's first
 * call spawns a daemon that inherits that call's environment, so the shim is
 * where each session's profile, socket dir and Chromium flags get decided.
 */
import {
  accessSync,
  chmodSync,
  constants as fsConstants,
  mkdirSync,
  readFileSync,
  realpathSync,
  renameSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs"
import { delimiter, join, resolve } from "node:path"
import { binDir, shimPath } from "./paths"

export const SHIM_VERSION = 2

const BINARY_NAME = "agent-browser"

/** Escapes a value for interpolation inside bash double quotes. */
function shellQuoted(value: string): string {
  return value.replace(/[\\"$`]/g, (char) => `\\${char}`)
}

export function renderShim(realBinary: string): string {
  return `#!/usr/bin/env bash
# cogpit-shim v${SHIM_VERSION} — routes agent-browser into Cogpit's managed browser tree.
# Regenerated by Cogpit on start; edits are lost.
set -euo pipefail
real="${shellQuoted(realBinary)}"
if [ ! -x "$real" ] || [ "$real" -ef "$0" ]; then
  echo "cogpit-shim: $real is not usable; restart Cogpit to refresh the shim" >&2
  exit 127
fi
valid_name() { local LC_ALL=C; [[ "$1" =~ ^[a-z0-9][a-z0-9_-]{0,39}$ ]]; }
valid_sid()  { local LC_ALL=C; [[ "$1" =~ ^[A-Za-z0-9_-]{1,80}$ ]]; }
[ -n "\${COGPIT_BROWSER_HOME:-}" ] || [ -n "\${HOME:-}" ] || exec "$real" "$@"
home="\${COGPIT_BROWSER_HOME:-$HOME/.cogpit/browser}"
name="\${AGENT_BROWSER_SESSION:-default}"
prev=""
for arg in "$@"; do
  if [ "$prev" = "--session" ]; then name="$arg"; break; fi
  case "$arg" in --session=*) name="\${arg#--session=}"; break;; esac
  prev="$arg"
done
valid_name "$name" || exec "$real" "$@"
if [[ "$name" == tmp-* ]]; then
  sid="\${COGPIT_SESSION_ID:-}"
  valid_sid "$sid" || sid="shared"
  export AGENT_BROWSER_SOCKET_DIR="$home/run/$sid"
  mkdir -p "$AGENT_BROWSER_SOCKET_DIR"
  exec "$real" "$@"
fi
profile="$home/profiles/$name"
mkdir -p "$profile" "$home/run/shared"
printf '%s\\n' "\${COGPIT_SESSION_ID:-}" > "$profile/.driver"
export AGENT_BROWSER_SOCKET_DIR="$home/run/shared"
export AGENT_BROWSER_PROFILE="$profile"
export AGENT_BROWSER_ARGS="--remote-debugging-port=0"
exec "$real" "$@"
`
}

function hasContent(path: string, script: string): boolean {
  try {
    return readFileSync(path, "utf8") === script
  } catch {
    return false
  }
}

export function ensureShim(realBinary: string | null): { path: string | null } {
  const path = shimPath()
  if (realBinary === null) {
    rmSync(path, { force: true })
    return { path: null }
  }
  const script = renderShim(realBinary)
  if (!hasContent(path, script)) {
    mkdirSync(binDir(), { recursive: true })
    const tmp = `${path}.tmp`
    writeFileSync(tmp, script, { mode: 0o755 })
    renameSync(tmp, path)
  }
  chmodSync(path, 0o755)
  return { path }
}

function canonical(dir: string): string {
  try {
    return realpathSync(dir)
  } catch {
    return resolve(dir)
  }
}

function isExecutableFile(candidate: string): boolean {
  try {
    accessSync(candidate, fsConstants.X_OK)
    return statSync(candidate).isFile()
  } catch {
    return false
  }
}

export function findRealAgentBrowser(env: NodeJS.ProcessEnv = process.env): string | null {
  const shimDir = canonical(binDir())
  for (const entry of (env.PATH ?? "").split(delimiter)) {
    if (!entry || canonical(entry) === shimDir) continue
    const candidate = join(entry, BINARY_NAME)
    if (isExecutableFile(candidate)) return candidate
  }
  return null
}
