#!/usr/bin/env bun
/**
 * The `cogpit` skill bundles the standalone cogpit-sessions and cogpit-memory
 * skills as reference files, so `npx skills add` installs all three as one unit.
 * The standalone skills stay the sources of truth; this script copies their
 * bodies into .claude/skills/cogpit/references/ and embeds all bundled skills
 * for distribution without runtime access to the source checkout.
 *
 * Pass --check in CI to fail when a generated copy has drifted.
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"

const ROOT = join(import.meta.dir, "..")
const DEST = join(ROOT, ".claude/skills/cogpit/references")

const SOURCES = [
  { from: ".claude/skills/cogpit-sessions/SKILL.md", to: "cogpit-sessions.md" },
  { from: "packages/cogpit-memory/skill/SKILL.md", to: "cogpit-memory.md" },
  { from: "docs/remote-workspaces.md", to: "remote-workspaces.md" },
] as const

function render(from: string): string {
  const body = readFileSync(join(ROOT, from), "utf8").replace(/^---\n[\s\S]*?\n---\n+/, "")
  return `<!-- Generated from ${from} by scripts/sync-cogpit-skill.ts. Edit the source, then run \`bun run sync-cogpit-skill\`. -->\n\n${body}`
}

const checkOnly = process.argv.slice(2).includes("--check")
const rendered: { from: string; to: string; path: string; content: string }[] = SOURCES.map((source) => ({
  ...source, path: join(DEST, source.to), content: render(source.from),
}))
rendered.push({
  from: "docs/remote-workspaces.md",
  to: ".claude/skills/cogpit-sessions/references/remote-workspaces.md",
  path: join(ROOT, ".claude/skills/cogpit-sessions/references/remote-workspaces.md"),
  content: render("docs/remote-workspaces.md"),
})

const skillSources = {
  cogpit: ".claude/skills/cogpit",
  "cogpit-browser": ".claude/skills/cogpit-browser",
  "cogpit-sessions": ".claude/skills/cogpit-sessions",
  "cogpit-memory": "packages/cogpit-memory/skill",
}
function skillFiles(directory: string, prefix = ""): Record<string, string> {
  return Object.fromEntries(readdirSync(directory, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name)).flatMap((entry): [string, string][] => {
    const name = prefix + entry.name
    if (entry.isDirectory()) return Object.entries(skillFiles(join(directory, entry.name), `${name}/`))
    if (!entry.name.endsWith(".md")) return []
    const generated = rendered.find((file) => file.path === join(directory, entry.name))
    return [[name, generated?.content ?? readFileSync(join(directory, entry.name), "utf8")]]
  }))
}
const skills = Object.fromEntries(Object.entries(skillSources).map(([name, directory]) => [name, skillFiles(join(ROOT, directory))]))
rendered.push({
  from: "bundled skill sources",
  to: "server/agents/bundledSkills.ts",
  path: join(ROOT, "server/agents/bundledSkills.ts"),
  content: `// Generated by scripts/sync-cogpit-skill.ts. Edit the Markdown sources, then regenerate.\nexport const BUNDLED_SKILLS: Readonly<Record<string, Readonly<Record<string, string>>>> = ${JSON.stringify(skills, null, 2)}\n`,
})

if (checkOnly) {
  const drifted = rendered.filter(({ path, content }) => {
    try {
      return readFileSync(path, "utf8") !== content
    } catch {
      return true
    }
  })
  if (drifted.length > 0) {
    console.error("The cogpit skill references are out of sync:")
    for (const { to } of drifted) console.error(`  - ${to}`)
    console.error("Run `bun run sync-cogpit-skill` and commit the generated copies.")
    process.exit(1)
  }
  console.log(`Verified ${rendered.length} cogpit skill references`)
  process.exit(0)
}

mkdirSync(DEST, { recursive: true })
for (const { to, path, content } of rendered) {
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, content)
  console.log(`  synced ${to}`)
}
