import { join } from "node:path"
import { writeIfChanged } from "../browser/files"
import { binDir } from "../browser/paths"
import { CLI_NAME } from "./commands"

/**
 * Installs `cogpit-session` beside the agent-browser shim in `~/.cogpit/bin`,
 * which Cogpit puts first on every agent's PATH.
 *
 * The script needs a JavaScript runtime, and an agent's machine may have no
 * Node on PATH, so the launcher runs it with the binary serving Cogpit right
 * now: Electron (as Node), Bun or Node. It is rewritten on every start, so a
 * moved or updated app repoints it.
 */

const SCRIPT_NAME = `${CLI_NAME}.mjs`
const HEADER = `${CLI_NAME} — regenerated by Cogpit on start; edits are lost.`

export function sessionCliPath(platform: NodeJS.Platform = process.platform): string {
  return join(binDir(), platform === "win32" ? `${CLI_NAME}.cmd` : CLI_NAME)
}

/** Forwards argv to `POST /api/session-cli` and prints what the server answers. */
export function renderSessionCliScript(): string {
  return `// ${HEADER}
import { randomUUID } from "node:crypto"
import { readFileSync } from "node:fs"
import { request } from "node:http"
import { homedir } from "node:os"
import { join } from "node:path"

// Safe to repeat after a dropped connection: reads, and \`new\`, which the
// server creates once per invocation id.
const REPEATABLE = new Set(["new", "wait", "status", "result", "children", "help"])

function port() {
  if (process.env.COGPIT_PORT) return process.env.COGPIT_PORT
  try {
    return readFileSync(join(homedir(), ".cogpit", "port"), "utf8").trim() || "19384"
  } catch {
    return "19384"
  }
}

function post(url, payload) {
  return new Promise((resolve, reject) => {
    const req = request(url, {
      method: "POST",
      headers: { "content-type": "application/json", "content-length": Buffer.byteLength(payload) },
    }, (res) => {
      let body = ""
      res.setEncoding("utf8")
      res.on("data", (chunk) => { body += chunk })
      res.on("end", () => resolve({ status: res.statusCode ?? 0, body }))
    })
    req.on("error", reject)
    req.end(payload)
  })
}

const args = process.argv.slice(2)
const argv = args.map((arg) => (arg === "-" ? readFileSync(0, "utf8") : arg))
const url = \`http://127.0.0.1:\${port()}/api/session-cli\`
const payload = JSON.stringify({
  argv,
  cwd: process.cwd(),
  invocationId: randomUUID(),
  callerSessionId: process.env.COGPIT_SESSION_ID || undefined,
})

let response
for (let attempt = 1; ; attempt++) {
  try {
    response = await post(url, payload)
    break
  } catch (error) {
    const refused = error.code === "ECONNREFUSED"
    if (attempt >= 4 || !(refused || REPEATABLE.has(argv[0]))) {
      console.error(\`${CLI_NAME}: cannot reach Cogpit at \${url} (\${error.code || error.message}). Is Cogpit running? Set COGPIT_PORT if it listens elsewhere.\`)
      process.exit(1)
    }
    await new Promise((resolve) => setTimeout(resolve, 1000 * attempt))
  }
}

if (response.status !== 200) {
  let message = response.body
  try { message = JSON.parse(response.body).error ?? message } catch {}
  console.error(\`${CLI_NAME}: \${response.status === 404 ? "this Cogpit is too old for ${CLI_NAME}; update it" : message}\`)
  process.exit(1)
}
const { exitCode, stdout, stderr } = JSON.parse(response.body)
if (stdout) process.stdout.write(stdout)
if (stderr) process.stderr.write(stderr)
process.exitCode = exitCode
`
}

function shellQuoted(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`
}

export function renderPosixLauncher(runtime: string): string {
  return `#!/bin/sh
# ${HEADER}
runtime=${shellQuoted(runtime)}
script="$(dirname "$0")/${SCRIPT_NAME}"
if [ -x "$runtime" ]; then
  ELECTRON_RUN_AS_NODE=1 exec "$runtime" "$script" "$@"
fi
exec node "$script" "$@"
`
}

export function renderCmdLauncher(runtime: string): string {
  return `@echo off\r\nrem ${HEADER}\r\nsetlocal\r\nset ELECTRON_RUN_AS_NODE=1\r\n"${runtime}" "%~dp0${SCRIPT_NAME}" %*\r\n`
}

export function ensureSessionCli(
  runtime: string = process.execPath,
  platform: NodeJS.Platform = process.platform,
): void {
  const dir = binDir()
  writeIfChanged(join(dir, SCRIPT_NAME), renderSessionCliScript(), 0o644)
  writeIfChanged(join(dir, CLI_NAME), renderPosixLauncher(runtime), 0o755)
  if (platform === "win32") writeIfChanged(sessionCliPath(platform), renderCmdLauncher(runtime), 0o755)
}

/** Startup hook: a read-only home costs agents the CLI and nothing else. */
export function installSessionCli(): void {
  try {
    ensureSessionCli()
  } catch (error) {
    console.error(`[${CLI_NAME}] install failed; agents cannot use it until the next start.`, error)
  }
}
